output_dir: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/outputs
data:
  path: /PHShome/dzm44/data/Dataset_8-1-2023/preprocessed
  dataset: bwh_er_data
  max_reports_considered: null
  #max_reports_considered: 64
  mimic_folder_for_demographics: /PHShome/dzm44/data/Dataset_8-1-2023
write_to_cache:
  slice: '10000,20000'
  split: train
  run_through_episode: false
  subset_file: null
  max_observed_reports: 20
  cache_dir: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_train_cache_2
sample_subset:
  split: train
  subset_file: train_subset.pkl
  negatives_percentage: .2
  gender: null
  race: null
  seed: 0
device: cuda
training:
  limit_train_size: null
  limit_val_size: null
  # train_subset_file: train_subset.pkl
  train_subset_file: null
  val_subset_file: null
  resume_from: null
  num_epochs: 600
  # num_episodes: 64
  num_episodes: 512
  batch_size: 1
  accumulate_grad_batches: 64 #128
  actor_lr: 1e-5
  actor_warmup: 200
  actor_training_steps: 10000
  critic_lr: 1e-5
  critic_warmup: 200
  critic_training_steps: 10000
  checkpoint_every: 5
  # objective_optimization: ppo_gae
  objective_optimization: supervised
  # objective_optimization: mix_objectives
  clear_gpu: true
  freeze_actor: null
  # freeze_actor: "everything_but_query"
  skip_risk_prediction: false
  # skip_risk_prediction: true
  skip_query_prediction: true
  shape_reward_with_attn: false
  # shape_reward_with_attn: true
  val_every: 5
  trainmetrics_every: 5
  query_policy: 'zeros'
  rp_policy: 'zeros'
  eval_query_policy: 'zeros'
  eval_rp_policy: null
  # val_max_num_episodes: 300
  # trainmetrics_max_num_episodes: 300
  val_max_num_episodes: 1
  trainmetrics_max_num_episodes: 1
  max_trajectory_length: 2
  val_max_trajectory_length: 2
  trainmetrics_max_trajectory_length: 2
  use_random_start_idx: true
  eval_val_use_random_start_idx: true
  eval_train_use_random_start_idx: true
  max_observed_reports: 20
  eval_val_max_observed_reports: 20
  eval_train_max_observed_reports: 20
eval:
  split: val1
  limit_eval_size: null
  max_num_episodes: null
  # max_trajectory_length: null
  max_trajectory_length: 2
  random_query_policy: true
  random_rp_policy: false
  use_random_start_idx: true
  max_observed_reports: 20
  seed_offset: 0
  checkpoint: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/outputs/wandb/run-20230812_004109-oomrpc0z/files/ckpt_epoch=65_updates=3107.pt
mix_objectives:
  coefficient: .5 # represents the proportion of the supervised objective
ppo_gae:
  gamma: 0.99
  lam: 0.95
  epsilon: .5
  sub_epochs: 1
  use_adv_norm: true
  # entropy_coefficient: .01
  entropy_coefficient: 0
  use_grad_clip: true
  log_reward: false
  # log_reward: true
  only_train_critic: false
  # only_train_critic: true
  only_train_query_prediction: true
supervised:
  sub_epochs: 1
  use_grad_clip: true
  entropy_coefficient: 0
  only_train_risk_prediction: true
  # only_train_risk_prediction: false
  query_supervision_type: targets
ppo_dae:
  epsilon: .5
env:
  # env_type: EHRDiagnosisEnv-v0
  env_type: FlanEHRDiagnosisEnv-v0
  # env_type: MistralEHRDiagnosisEnv-v0
  # llm_name: 'google/flan-t5-xxl'
  llm_name: '/PHShome/dzm44/models/flan-t5-xxl'
  # llm_name: 'mistralai/Mistral-7B-Instruct-v0.2'
  # llm_name: '/PHShome/dzm44/models/models--mistralai--Mistral-7B-Instruct-v0.2'
  # fmm_name: 'all-MiniLM-L6-v2'
  fmm_name: '/PHShome/dzm44/models/all-MiniLM-L6-v2'
  train_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_train_cache_flan_2
  val1_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val1_cache_flan_2
  val2_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val2_cache_flan_2
  test_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_test_cache_flan_2
  # train_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_train_cache_mistral_2
  # val1_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val1_cache_mistral_2
  # val2_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val2_cache_mistral_2
  # test_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_test_cache_mistral_2
  reward_type: 'continuous_independent'
  other_args:
    top_k_evidence: 3
    num_future_diagnoses_threshold: 0
    match_confident_diagnoses: false
    match_potential_diagnoses: false
    true_positive_minimum: 0
    add_risk_factor_queries: false
    limit_options_with_llm: true
    use_confident_diagnosis_mapping: false
    stop_after_first_target: false
    skip_instances_with_gt_n_reports: 200
    add_diagnosis_options_from_caches:
      - /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_train_cache_flan_2
    added_diagnosis_options_threshold: 10
    limit_evidence_updates_to_k_reports: 1
actor:
  # type: normal
  # type: dirichlet
  # type: beta
  type: delta
  shared_params:
    static_diagnoses: null
    # static_diagnoses:
    #   - cancer (diagnosis)
    #   - pneumonia (diagnosis)
    #   - pulmonary edema (diagnosis)
    static_bias_params: null
    train_static_bias_params: null
    # train_static_bias_params: # for training
    #   - [-1.4396936453085785]
    #   - [-0.5889434030299426]
    #   - [-0.05625351040116628]
    eval_static_bias_params: null
    # eval_static_bias_params: # for inference
    #   - [-2.642675509576076]
    #   - [-1.9572920156106348]
    #   - [-1.5961686236710402]
    embedder_type: interpretable
    # embedder_type: bert
    # model_name: emilyalsentzer/Bio_ClinicalBERT
    model_name: /PHShome/dzm44/models/Bio_ClinicalBERT
    # model_name: roberta-base
    diagnosis_bias: true
    use_attn: false
    embedding_batch_size: 16 #32
    grad_checkpointing: true
    ignore_evidence: false
    ignore_no_evidence_found: true
    randomly_drop_evidence: null
    # randomly_drop_evidence: .2
    separate_bias: true
    constant_denominator: 10
    use_raw_sentences: false
    limit_num_sentences: 1000
  normal_params:
    stddev_min: .02
    stddev_max: 1
  dirichlet_params:
    # concentration_min: .2
    concentration_min: 1
    # concentration_min: 5
  beta_params:
    concentration_min: 1
    init_concentration0: 100
  delta_params: {}
critic:
  static_diagnoses: null
  # static_diagnoses:
  #   - cancer
  #   - pneumonia
  #   - pulmonary edema
  embedder_type: interpretable
  # embedder_type: bert
  # model_name: emilyalsentzer/Bio_ClinicalBERT
  model_name: /PHShome/dzm44/models/Bio_ClinicalBERT
  diagnosis_bias: true
  # model_name: roberta-base
  embedding_batch_size: 8 #32
  grad_checkpointing: false
  ignore_no_evidence_found: false
  randomly_drop_evidence: null
  # randomly_drop_evidence: .2
